# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: push
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-chrome@latest
    - name: Setup display
      run: |
          sudo apt update
          sudo apt-get install xvfb -y
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Cache Node Modules
      uses: actions/cache@v1
      with:
        path: src/main/webapp/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-node_modules
    - name: "Install Angular dependencies"
      run: npm install
      working-directory: src/main/webapp
    - name: "[Angular] Build and analyze"
      run: |
          Xvfb :1 -screen 0 1920x1080x24 &
          export DISPLAY=:1
          npm run coverage
      working-directory: src/main/webapp
    - name: "[Java] Build and analyze"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=vepo_microblogging \
                                                                                -Dsonar.sources=src/main/java,src/main/webapp \
                                                                                -Dsonar.javascript.lcov.reportPaths=src/main/webapp/coverage/**/lcov.info
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
